# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d994dfec621c22b0b37a4a47156ccfc836e9d2452b82d84d8f64f5cd43f22a5023a615c9b8e4cb9b726dba1af000894dd58fe0ffbacb9348ac9ec8b065ef7e8e

test:
  secret_key_base: 38680cc97c09e3fd648b85fb8d640ef2206b3a1231ac41366a5e5c49609991f38e0eb9767c3296dbd3689a40e4f09d5dd028a6444a7db4cade8749dd9b666fa7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
